# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6527811b8d90532809feacb01a39b80cd8d6794eb0f38ec4608e7933aea8c0c66cfaf4cc9a8adb12ccb7ab500ca77b79cfe7dc5530a56c9cc1278744022749fa

test:
  secret_key_base: 06a613a05ed515a578088ced3b31099d46b87ba63e5b948222a07d4049bb043701aac80e263066bf868762f0fa28780b7590cf039377709a3eff4c9e6715b615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
